### ISSUE TITLE
Android : THREAD WARNING

### ISSUE THREAD

**Issue by holospeed** [Telerik-Verified-Plugins/Stripe#15]
On Android, when I try to make a test charges request the process fail.

Android Studio console : THREAD WARNING: exec() call to Stripe.process blocked the main thread for 28ms. Plugin should use CordovaInterface.getThreadPool().

**Comment by EddyVerbruggen** [comment]
That's just a friendly warning for the plugin dev, has nothing to do with your issue. Please dig into adb logcat or javascript console to find the real cause and let us know.

**Comment by holospeed** [comment]
The problem have been found and solved :)

I used live secret key but my account was in test mode. I changed it to test secret key and it works fine now. 
Strange, because under iOS I using live secret key with the same test account, but its work fine there... Is there any way to change the API key under Android whiteout reinstall the plugin ?

**Comment by EddyVerbruggen** [comment]
That depends on how you build it, but there's a `stripe_api_key` in `res/values/strings.xml`.

**Comment by holospeed** [comment]
Thank you! :)
